### ISSUE TITLE
Suggestion for better game-play

### ISSUE THREAD

**Issue by snehitvaddi** [abhinavnayak11/Hand-Cricket#2]
I loved your project and your efforts in data collection. 
In the gameplay, I feel having synchronization (ie. both computer hand and your hand at the same time) would be more appealing.
Maybe you can use some counter so that both systems and you can play at the right point of time.

**Comment by abhinavnayak11** [comment]
Regarding synchronization, this is how the code is:
1. User presses space to play and will place his hand in the frame
2. Wait for 1 second (for user to position his hand)
3. After 1 second, 2 operations happen: 
     1. generate new number, get it's image. Display both number and image
     2. Capture the right frame and predict the number. Display the number.

I can remove that 1 second delay. But with that I was sometimes not able to position my hands before my hand image is captured.

You can fork the repo, try changing the delay time or try Incorporating any other way to improve synchronization and create pull request.
